### PR TITLE
Update compounds.yml

### PR DESCRIPTION
**Pull request by cosalich**
Corrected teaspoon concentrations to accurately reflect the fact that volume = mass/density. That means 1tsp (5mL for simplicity) needs to be multiplied by the density to get grams, then must be multiplied by 1000 for milligrams. Simple stuff.

Prior to these changes, concentrations were off by roughly half which caused the calculator to recommend adding twice as much of each fert as necessary. This would result in vast over-fertilization and probably some serious algae issues.

I'd love to do the rest of the calculations, but I'm unable as I have no idea what the proprietary formulae contain and I don't understand some of the notation (I never was a big chem guy). This at least covers the macros.

### CODE REVIEW

**Comment by flores** [comment]
Awesome, thank you.

I will need a minute before getting around to forums to update on this change, which is my only hesitation for the push.  However, if you feel like that won't be an issue I'm open to just pushing now/soon before getting an announcement together.

**Comment by cosalich** [comment]
No problem. I could update the forum myself, but I have absolutely no idea which forum you are referring to.

**Comment by flores** [comment]
That would be awesome.  I'm thinking the standard big ones: APC, TPT,
BarrReport, UKAPS...

Let me know if that does work for you and if so we can merge this in easily
and bring it live.

**Comment by flores** [comment]
I still haven't moved on this, so merging it now.  Thanks again for the pull request.

**Comment by zorfox** [comment]
You're ignoring the dead space in volumetric measures. Volume = mass/density when the volume is pure. There are air spaces in each compound that cannot be calculated for in this way. Example, 5 ml of KNO3 would have a weight of 10.55 grams if the volume was 100% KNO3 (KNO3 has a density of 2.11 g/cm³). However, the volume is not pure KNO3. There are air spaces between each particle. Weigh a teaspoon of KNO3. It's roughly 5,200mg not 10.55 grams.

**Pull request merged**
